default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['POSTGRESQL_USERNAME'] %>
  password: <%= ENV['POSTGRESQL_PASSWORD'] %>
development:
  <<: *default
  database: sscatfact_front_development
test:
  <<: *default
  database: sscatfact_front_test
production:
  <<: *default
  database: sscatfact_front_production